### ISSUE TITLE
Permission denied to create work tree

### ISSUE THREAD

**Issue by AlexBeakes** [inceye/linux-autoinstall#3]
In deploy-internal install_additional function
![20210215_195110.jpg](https://user-images.githubusercontent.com/78613084/107974468-b291b280-6fc7-11eb-8951-ea7001523246.jpg)

**Comment by AndyGozas** [comment]
Actually, after installing each package, you cd back to /, and you run git clone before going into linux-autoinstall/tmp , so the user actually tries to git clone into /, which he does not have enough permissions to do -- easy fix is just removing one cd / after the tmp directory setup and changing all the next cd / to cd ../, which I've just done
